""" Manages the authentication token generated by the OAuth2 implementation of our login system """

# pylint: disable=too-few-public-methods
from typing import List, Optional

from pydantic import BaseModel

class Token(BaseModel):
    """ Base model for the access token """
    access_token: str
    token_type: str

class TokenData(BaseModel):
    """ Contains information about the user and their auth scopes """
    username: Optional[str] = None
    scopes: List[str] = []
