name: Production Build Deployment to DevOps Server

on:
  # Disabled until Production is migrated to another cloud provider
  # This workflow will run nightly instead to avoid changes being deployed
  # during daytime hours.
  # For deployments that require database migration; workflow dispatch
  # will be used instead to time the manual executation of the migration
  # workflow_run:
  #   workflows: [Compile & Publish]
  #   types:
  #     - completed
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  ROSALUTION_VERSION: ${{ vars.VERSION_BUILD_TAG }}

jobs:
  docker-shell-stack-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Production Rosalution Build to Developer DevOps Server
        run: sudo -E docker stack deploy --with-registry-auth --compose-file docker-compose.staging.yml rosalution-prod
