name: Rosalution Paper Draft

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'paper.md'
      - 'paper.bib'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: JOSS pandoc paper draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper.pdf
