name: Node.js CI

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: frontend

jobs:
  nodejs-ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.2]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test:coverage