name: Node.js CI

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: frontend

jobs:
  nodejs-ci:

    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    strategy:
      matrix:
        node-version: [26.3]

    steps:
    - uses: actions/checkout@v7
    - name: Install pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 11
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
        cache-dependency-path: frontend/pnpm-lock.yaml
    - name: Install dependencies
      run: pnpm install
    - run: pnpm lint
    - run: pnpm test:coverage