name: Node.js CI

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: frontend

jobs:
  nodejs-ci:

    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    strategy:
      matrix:
        node-version: [20.8]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test:coverage