name: System Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  system-tests:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    
    steps:
    - uses: actions/checkout@v4
    - name: Running the setup.sh script
      run: |
        sh setup.sh
    - name: Cypress tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: system-tests
        browser: electron
        headed: false
        start: docker compose up --build -d
        wait-on: 'https://local.rosalution.cgds'
        wait-on-timeout: 120
      env:
        # Avoids self-signed cert error: https://github.com/cypress-io/github-action/issues/154
        NODE_TLS_REJECT_UNAUTHORIZED: 0